# Generated by Django 5.0.4 on 2024-05-07 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('building_from', models.CharField(max_length=30, verbose_name='Building From')),
                ('room_from', models.CharField(max_length=30, verbose_name='Room From')),
                ('building_to', models.CharField(max_length=30, verbose_name='Building To')),
                ('room_to', models.CharField(max_length=30, verbose_name='Room To')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('duration', models.IntegerField(default=5, verbose_name='Duration (minutes)')),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Hall Pass',
                'verbose_name_plural': 'Hall Passes',
            },
        ),
    ]
