# Generated by Django 5.0.4 on 2024-05-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='hallpass',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passes_from_staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='building_from',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='building_to',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='room_from',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='room_to',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hallpass',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='passes_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
