# Generated by Django 5.0.4 on 2024-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0002_remove_hallpass_teacher_hallpass_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpass',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
