# Generated by Django 5.0.4 on 2024-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0004_alter_hallpass_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpass',
            name='is_extended',
        ),
    ]
