# Generated by Django 5.0.4 on 2024-05-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0005_remove_hallpass_is_extended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallpass',
            options={'ordering': ('-status',), 'verbose_name': 'Hall Pass', 'verbose_name_plural': 'Hall Passes'},
        ),
    ]
