# Generated by Django 5.0.4 on 2024-05-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0006_alter_hallpass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallpass',
            options={'verbose_name': 'Hall Pass', 'verbose_name_plural': 'Hall Passes'},
        ),
    ]
