# Generated by Django 5.0.4 on 2024-05-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0007_alter_hallpass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpass',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended'), ('Expired', 'Expired')], default='Active', max_length=10),
        ),
    ]
