# Generated by Django 5.0.4 on 2024-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0011_alter_hallpass_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpass',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
