# Generated by Django 5.0.4 on 2024-05-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0012_alter_hallpass_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpass',
            name='is_hidden',
        ),
    ]
